### Alf Global Properties
dir.root=c:\Work\ACS
dir.contentstore=c:\Work\ACS\contentstore
dir.contentstore.deleted=c:\Work\ACS\contentstore.deleted

### DB Config
db.username=alfresco
db.password=__DB_PASSWORD_PLACEHOLDER__
solr.sharedSecret=__SOLR_SHARED_SECRET__
