
name: Update Alfresco Global Properties

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Target Deployment Environment'
        required: true
        default: 'Development'
        type: choice
        options:
          - Development
          - Staging

jobs:
  update-file:
    runs-on: [self-hosted, "${{ inputs.environment == 'Development' && 'MyPC-1' || inputs.environment == 'Staging' && 'IBM-PC' }}"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: true
          sparse-checkout-cone-mode: false # Fixes the "not a directory" error
          sparse-checkout: 'config/alfresco-global.properties'

       # 📁 Step 1: Dynamically determine and export the correct target path
      - name: Resolve Environment Configuration
        id: config
        shell: cmd
        run: |
          if [ "${{ inputs.environment }}" = "Development" ]; then
             echo "TARGET_PATH=D:\Work\JBR\Code\ACS Target\assumedTarget\\" >> $GITHUB_ENV
             echo "SCRIPT_PATH=D:\Work\JBR\Code\ACS Target\scripts\\" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" = "Staging" ]; then
             echo "TARGET_PATH=C:\Work\ACS\Taarget\\" >> $GITHUB_ENV
             echo "SCRIPT_PATH=C:\Work\ACS\Scripts\\" >> $GITHUB_ENV

      - name: Copy File to Target Dir
        shell: cmd
        run: |
          echo Deploying to target path: "%TARGET_PATH%"
          
          if not exist "%TARGET_PATH%" mkdir "%TARGET_PATH%"
          
          if exist "config\alfresco-global.properties" (
              xcopy "config\alfresco-global.properties" "%TARGET_PATH%" /Y
          ) else (
              echo ERROR: Properties file not found in repo checkout! && exit 1
          )
      
     #   shell: powershell -ExecutionPolicy Bypass -Command ". '{0}'"
     #   run: |
          # init
     #     $sourceFile = "config/alfresco-global.properties"
     #     $targetPath = "D:\Work\JBR\Code\ACS Target\assumedTarget\"

      #    Copy-Item -Path $sourceFile -Destination $targetPath -Force
       #   Write-Host "File Config Updated"

      - name: Run Success Message
        shell: cmd
        run: |
          echo Executing startup script from: "%SCRIPT_PATH%"
          cd /d "%SCRIPT_PATH%"
          call startup.bat
