
name: Update Alfresco Global Properties

on:
  workflow_dispatch:
    
  push:
    branches: [main]
    paths:
      - 'config/alfresco-global.properties'  # When this file is updated

jobs:
  update-file:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'alfresco-global.properties'

      - name: Copy File to Target Dir
        run: |
          # init
          $sourceFile = "config/alfresco-global.properties"
          $targetPath = "D:\Work\JBR\Code\ACS Target\assumedTarget\"

          Copy-Item -Path $sourceFile -Destination $targetPath -Force
          Write-Host "File Config Updated"

      - name: Run Success Message
        shell: cmd
        run: |
          call D:\Work\JBR\Code\ACS Target\scripts\startup.bat
